### ISSUE TITLE
Spec incorrectly documents "owner" role

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/spec#1]
> There are 3 constant role IDs that servers MUST apply based on user state:
> * `_owner`, given to the first user registered to the server only
> * (`_user`, `_guest`)

This is not how `_owner` works, as discussed [here](https://github.com/decent-chat/decent/commit/873bf7c291b3c317b1661b07699f47e4904eed45#r28037953). TL;DR, this is the behaviour:

> Automatically make an "owner" role and have a CLI command to apply that. This is basically what we did already - make-admin - so it's what I do now. It took very little effort to implement. This option is bad because it means having a dumb, builtin, hard-coded role (that can't even be deleted because it'd just be regenerated each time), but there's not much we can do about that besides option 1 above.

Note the "Owner" role cannot be renamed or deleted. Also, it doesn't have the ID "Owner" - its ID is randomly generated just like any user-created role (the only special thing about it is its name "Owner").

I'm not sure it should *strictly* be part of the spec or not, since it's a dumb hack, anyways. But what's in the spec now is for sure wrong.

**Comment by bates64** [comment]
Oops, okay. Fixing.

**Comment by towerofnix** [comment]
Fix looks good, thanks!
