### ISSUE TITLE
New roles are prioritized above the role-creator's own roles

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/spec#15]
When a new role is created, it is added to the role priority order such that it is the most prioritized. This means it's more prioritized than the roles of whoever created it, and as such, cannot be reordered by that user (or any other user, since all of their roles will also be less prioritized than the new role). Would it make sense that the new role is added to be as prioritized as it can be *under* the creating user's highest role?

**Comment by bates64** [comment]
Yes
