### ISSUE TITLE
Separate permissions for creating/deleting/modifying roles and giving/taking them?

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/spec#7]
Right now we simply have a `manageRoles` permission that does *all* of that:

> `manageRoles`: Allows creation/deletion/modification/granting/revoking of roles under you.

Should this be split into two different roles, as described in this issue's title? Admins may want to give specific users the ability to grant and revoke roles but not creation/deletion/modification of them.

**Comment by bates64** [comment]
Yep.

**Comment by bates64** [comment]
`manageRoles` - create, delete, modify, reorder
`grantRoles` - grant, revoke
