### ISSUE TITLE
Who can change the role prioritization order? (I.e: a permission for changing role order)

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/spec#8]
I'm thinking "you can only change the order of roles below you", i.e. you cannot put any role above (more prioritized) than a role that is above you, and you cannot change the order of any roles above you.

The thing is, roles aren't strictly above or below you... and that makes managing the role order a lot more complicated. I think it would simplify things greatly to simply have a change-role-order permission. This does make anyone who has that permission effectively a god (since they could put, for example, a role that denies any permissions above the admin role).

Side-question: What happens if someone re-orders the prioritization order so that they, and all other users, end up *losing* the ability to re-order it? (E.g. putting a role with `manageRoleOrder: false` on top.) I guess a simple workaround would be to prevent making a change that would take `manageRoleOrder` from the requesting user.

Ping @heyitsmeuralex - this blocks 1.0.0.

**Comment by PullJosh** [comment]
How is this handled on existing platforms (like Discord)?

**Comment by towerofnix** [comment]
@PullJosh Discord has a more concrete view of "this role is above that role" - here's a screenshot from the perspective of someone who has the "middle role" (which has the "manage roles" permission):

!["Highest role", "Higher role", and "Middle role", all with "locked" icons. "Low role" and "Lowest role" both without "locked" icons.](https://user-images.githubusercontent.com/9948030/39669597-dd6aa9c6-50c6-11e8-837c-eb5968cb24b4.png)

So that user can re-order "low role" and "lowest role", but can't put them above "middle role", or change any options (order or permissions) of "middle role" and above.

**Comment by bates64** [comment]
I like the way Discord does it, if I'm honest. They should need `manageRoles` (manage/reorder any roles below you), though - I don't want people with the `'muricans` role to be able to reorder the color roles, for example!

>Side-question: What happens if someone re-orders the prioritization order so that they, and all other users, end up losing the ability to re-order it? (E.g. putting a role with manageRoleOrder: false on top.) I guess a simple workaround would be to prevent making a change that would take manageRoleOrder from the requesting user.

Discord disallows making a change that would lock one out.

**Comment by bates64** [comment]
> The thing is, roles aren't strictly above or below you...

Surely this is based on the role order?

```
role order = [ "high", "med", "low", "lowest" ]
(med has manageRoles: true)
```

Joe has the `med` role, meaning he **can** edit/reorder the `low` and `lowest` roles, but **not** `high` or `med`. Since he cannot grant permissions he does not have himself, it's safe to allow him to edit the lower roles.

**Comment by towerofnix** [comment]
Yeah, okay, you're right :)

Discord's mechanic probably does work (as you've pointed out) and is intuitive enough.

> Discord disallows making a change that would lock one out.

Okay, sounds good. I figured that would be the best way to go about it.

**Comment by towerofnix** [comment]
Reopening this because it needs to actually be implemented into the spec, which currently doesn't have any rules on who can reorder what roles.

Should be added as a subpoint under "`roleIDs` (array of IDs)" and explain the range of what roles a user can/cannot reorder. (My understanding is "the user can change all roles below their highest role, and not including their highest role" - is this correct?) Should mention, in another subpoint, that the order cannot be changed such that the user would not have the `manageRoles` permission.
